services:
  frontend:
    image: lstz/reusableform:latest
    container_name: rfd_frontend
    restart: always
    ports:
      - '3301:3301'
    networks:
      - rfd_network

networks:
  rfd_network:
    external: true
